name             'cespi_mysql'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures cespi_mysql'
long_description 'Installs/Configures cespi_mysql'
version          '0.1.0'

depends 'mysql-multi', '~> 1.4.1'
depends 'mysql',       '~> 5.6.0'
