name             'mo_mysql'
maintainer       'Christian A. Rodriguez & Leandro Di Tommaso'
maintainer_email 'chrodriguez@gmail.com leandro.ditommaso@mikroways.net'
license          'MIT'
description      'Installs/Configures mo_mysql'
long_description 'Installs/Configures mo_mysql'
version          '1.0.0'

depends 'mysql-multi',         '~> 2.1.2'
depends 'mysql',               '~> 6.0.0'
depends 'mysql_tuning',        '~> 0.4.0'
depends 'chef-sugar',          '~> 2.5.0'
